### ISSUE TITLE
Installation ?

### ISSUE THREAD

**Issue by zakblacki** [Killassa/LoupGarouUHC#1]
Bonjour,

J'aimerais savoir si ce projet est déjà opérationnel ? et comment l'installer 

Merci,

**Comment by Killassa** [comment]
Hello,

Non, je suis désolé celui-ci n'est pas terminé.


Cependant il est possible d'utiliser celui-ci, réalisé par une autre
personne :

https://www.spigotmc.org/resources/loup-garou-uhc-werewolf-uhc.73113/

Bonne journée.
